### ISSUE TITLE
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:852)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Set java.util.Map.entrySet()' on a null object reference
	at net.minecraft.client.main.Main.main(SourceFile:116)
	... 5 more


### ISSUE THREAD

**Issue by JeffTheKillerVNYT991** [JeffTheKillerVNYT991/Minecraft#1]

**Comment by JeffTheKillerVNYT991** [comment]
Test
